entrada = int(input('Digite um número para saber sua tabuada: '))
print('-'* 12)
print(f'{entrada} X  1 = {entrada * 1}')
print(f'{entrada} X  2 = {entrada * 2}')
print(f'{entrada} X  3 = {entrada * 3}')
print(f'{entrada} X  4 = {entrada * 4}')
print(f'{entrada} X  5 = {entrada * 5}')
print(f'{entrada} X  6 = {entrada * 6}')
print(f'{entrada} X  7 = {entrada * 7}')
print(f'{entrada} X  8 = {entrada * 8}')
print(f'{entrada} X  9 = {entrada * 9}')
print(f'{entrada} X 10 = {entrada * 10}')
print('-' * 12)

